print(True)
print(False)
print("*")
print(1 == 1)
print(1 == 2)
print(1 == 1.0)
print("1" == 1)
print(int("1") == 1)
print("*")
print("ham" == "ham")
print("ham" == "bacon")
print("ham" == "Ham")
print("*")
print(True == True)
print(False == False)
print(True == False)

print(True != False)